# Generated by Django 3.2 on 2021-07-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loginstance_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginstance',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
