# Generated by Django 3.2 on 2021-07-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loginstance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='staff_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wristband',
            name='band_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wristband',
            name='guard',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guard'),
        ),
        migrations.AlterUniqueTogether(
            name='loginstance',
            unique_together={('time', 'wristband')},
        ),
    ]
