# Generated by Django 3.2 on 2021-07-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210706_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wristband',
            name='guard',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band', to='core.guard'),
        ),
    ]
