# Generated by Django 3.2 on 2021-07-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210709_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginstance',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
